### ISSUE TITLE
All parented CS objects need to have their pos/rot/scale bound.

### ISSUE THREAD

**Issue by cbrisebois** [coherence/campfire-tutorial#2]
This is a new requirement from a couple versions ago and isn't a big deal but now there's an error message if CS objects that don't have pos/rot/scale bound are parented.  

For example when the simulator connects:
`11:02:15.551 (coherence) CoherenceSync: ObjectAnchor_-372428 needs to replicate the rotation and scale component of the transform or the behaviour of parenting is undefined. See: https://docs.coherence.io/v/1.3/manual/parenting-network-entities  context=CoherenceBridge (Coherence.Toolkit.CoherenceBridge) context=ObjectAnchor_-372428 (Coherence.Toolkit.CoherenceSync)        context=ObjectAnchor_-372428 (Coherence.Toolkit.CoherenceSync)`

This is because the localScale of the ObjectAnchor prefab is not bound.

**Comment by ccontinisio** [comment]
This has been long fixed! 👍🏻
